import type { IncomingSubmissionInput } from "./domain.ts";

const base = { sourceSystem: "event-suite-fixture", schemaVersion: "incoming-lead.v1", productCode: "event-suite", countryCode: "GB" as const, environment: "DEVELOPMENT" as const };

export const incomingLeadFixtures: IncomingSubmissionInput[] = [
  { ...base, sourceRecordId: "fixture-demo-001", sourceCategory: "DEMO_REQUEST", contactName: "Ava Morgan", submittedEmail: "ava@northstar-events.example", organisationName: "Northstar Events", sourceDetail: "Demo form", sourcePage: "/demo", occurredAt: "2026-08-27T09:00:00Z", consentState: "NOT_REQUIRED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-sales-001", sourceCategory: "TALK_TO_SALES", contactName: "Daniel Cole", submittedEmail: "daniel@brightline.example", organisationName: "Brightline Productions", sourceDetail: "Talk to sales form", sourcePage: "/contact-sales", occurredAt: "2026-08-27T10:15:00Z", consentState: "NOT_REQUIRED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-trial-001", sourceCategory: "TRIAL_STARTED", contactName: "Maya Singh", submittedEmail: "maya@northstar-events.example", organisationName: "Northstar Events", sourceDetail: "Event Suite trial", sourcePage: "/start", occurredAt: "2026-08-27T11:00:00Z", consentState: "NOT_REQUIRED", originalPayload: { organisationConfidence: "HIGH", tenantReference: "tenant-fixture-001", fixture: true } },
  { ...base, sourceRecordId: "fixture-template-001", sourceCategory: "TEMPLATE_DOWNLOAD", contactName: "Ava Morgan", submittedEmail: "ava@northstar-events.example", organisationName: "Northstar Events", templateIdentifier: "event-ops-template", sourceDetail: "Event Operations Template", sourcePage: "/templates/event-ops", occurredAt: "2026-08-25T08:00:00Z", consentState: "GRANTED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-resource-001", sourceCategory: "RESOURCE_DOWNLOAD", contactName: "Ava Morgan", submittedEmail: "ava@northstar-events.example", organisationName: "Northstar Events", resourceIdentifier: "event-operations-pack", sourceDetail: "Event Operations Planning Pack", sourcePage: "/resources/operations", occurredAt: "2026-08-24T08:00:00Z", consentState: "GRANTED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-resource-002", sourceCategory: "RESOURCE_DOWNLOAD", contactName: "Ava Morgan", submittedEmail: "ava@northstar-events.example", organisationName: "Northstar Events", resourceIdentifier: "pricing-guide", sourceDetail: "Event Suite Pricing Guide", sourcePage: "/resources/pricing", occurredAt: "2026-08-26T08:00:00Z", consentState: "GRANTED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-resource-003", sourceCategory: "RESOURCE_DOWNLOAD", contactName: "Ava Morgan", submittedEmail: "ava@northstar-events.example", organisationName: "Northstar Events", resourceIdentifier: "implementation-guide", sourceDetail: "Implementation Guide", sourcePage: "/resources/implementation", occurredAt: "2026-08-27T08:30:00Z", consentState: "GRANTED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-demo-002", sourceCategory: "DEMO_REQUEST", contactName: "Ava Morgan", submittedEmail: " AVA@NORTHSTAR-EVENTS.EXAMPLE ", organisationName: "Northstar Events", sourceDetail: "Later demo request", sourcePage: "/demo", occurredAt: "2026-08-28T08:00:00Z", consentState: "NOT_REQUIRED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-contact-002", sourceCategory: "PRODUCT_ENQUIRY", contactName: "Liam Green", submittedEmail: "liam@northstar-events.example", organisationName: "Northstar Events", sourceDetail: "Product enquiry", sourcePage: "/contact", occurredAt: "2026-08-27T12:00:00Z", consentState: "NOT_REQUIRED", originalPayload: { organisationConfidence: "HIGH", fixture: true } },
  { ...base, sourceRecordId: "fixture-ambiguous-001", sourceCategory: "RESOURCE_DOWNLOAD", contactName: "Jordan Lee", submittedEmail: "jordan@unknown-domain.example", organisationName: "The Festival Group", sourceDetail: "Resource download", sourcePage: "/resources", occurredAt: "2026-08-26T13:00:00Z", consentState: "UNKNOWN", originalPayload: { organisationConfidence: "AMBIGUOUS", fixture: true } },
  { ...base, sourceRecordId: "fixture-internal-001", sourceCategory: "INTERNAL_TEST", contactName: "Internal Test", submittedEmail: "test@company.example", organisationName: "Internal QA", sourceDetail: "QA fixture", sourcePage: "/internal", occurredAt: "2026-08-28T07:00:00Z", consentState: "NOT_REQUIRED", environment: "TEST", originalPayload: { fixture: true } },
  { ...base, sourceRecordId: "fixture-resource-002", sourceCategory: "RESOURCE_DOWNLOAD", contactName: "Ava Morgan", submittedEmail: "ava@northstar-events.example", organisationName: "Northstar Events", resourceIdentifier: "pricing-guide", sourceDetail: "Duplicate delivery", sourcePage: "/resources/pricing", occurredAt: "2026-08-26T08:00:00Z", consentState: "GRANTED", originalPayload: { organisationConfidence: "HIGH", fixture: true, duplicateDelivery: true } },
];
