"use client";

import { useEffect, useState } from "react";
import { canMutateCommercialData, type RevenueAccessState } from "../src/lib/auth/access";

type Run = { id: string; territory_code: string; focus: string; status: string; summary: { discovered?: number; qualified?: number; reviewRequired?: number; blockedOrRejected?: number; duplicates?: number }; ai_prospect_candidates: any[] };

export function AutonomousDiscoveryView({ access }: { access: RevenueAccessState }) {
  const [territory, setTerritory] = useState("ZA");
  const [focus, setFocus] = useState("ALL");
  const [runs, setRuns] = useState<Run[]>([]);
  const [message, setMessage] = useState("Loading saved discovery runs…");
  const [busy, setBusy] = useState(false);
  const canRun = canMutateCommercialData(access);
  useEffect(() => { fetch("/api/ai-sales/discovery").then(async (response) => { const value = await response.json(); if (!response.ok) throw new Error(value.message); setRuns(value.runs ?? []); setMessage(value.runs?.length ? "Saved discovery memory loaded." : "No discovery runs yet."); }).catch((error) => setMessage(error instanceof Error ? error.message : "Discovery memory could not be loaded.")); }, []);
  async function runDiscovery() {
    if (!canRun) return;
    setBusy(true); setMessage("Searching public event activity within the bounded discovery budget…");
    try { const response = await fetch("/api/ai-sales/discovery", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ territory, focus }) }); const value = await response.json(); if (!response.ok) throw new Error(value.message); setRuns((current) => [value.run, ...current]); setMessage("Discovery completed. No outreach was approved or sent."); } catch (error) { setMessage(error instanceof Error ? error.message : "Discovery failed."); } finally { setBusy(false); }
  }
  return <section className="lead-intelligence-section" aria-label="Autonomous Prospect Discovery">
    <div className="section-heading"><span className="label">AI SALES TEAM · AUTONOMOUS PROSPECT DISCOVERY V1</span><span className="muted">Operator-triggered · bounded public research · no autonomous outreach</span></div>
    <article className="intelligence-card"><div className="lead-form-grid"><label>Territory<select value={territory} disabled={!canRun || busy} onChange={(event) => setTerritory(event.target.value)}><option value="ZA">South Africa</option><option value="GB">United Kingdom</option></select></label><label>Focus<select value={focus} disabled={!canRun || busy} onChange={(event) => setFocus(event.target.value)}><option value="ALL">All opportunities</option><option value="EGS">EGS</option><option value="TICKETING">Ticketing</option><option value="ECC">ECC</option></select></label></div><p className="card-meta">Finds public events and responsible organisations without a supplied account or event. Each run is limited to eight candidate results and one web-search-backed AI request.</p><p role="status">{message}</p><button className="save-button" type="button" disabled={!canRun || busy} onClick={() => void runDiscovery()}>{busy ? "Finding prospects…" : "Find prospects"}</button>{!canRun ? <p className="card-meta">Viewer access is read-only.</p> : null}</article>
    {runs.map((run) => <article className="intelligence-card" key={run.id}><div className="card-top"><span className="pill">{run.status}</span><span className="muted">{run.territory_code === "ZA" ? "South Africa" : "United Kingdom"} · {run.focus}</span></div><p className="card-meta">{run.summary?.discovered ?? 0} found · {run.summary?.qualified ?? 0} qualified · {run.summary?.reviewRequired ?? 0} review required · {run.summary?.blockedOrRejected ?? 0} blocked/rejected · {run.summary?.duplicates ?? 0} duplicates</p>{(run.ai_prospect_candidates ?? []).map((candidate: any) => { const intelligence = candidate.prospect_intelligence ?? {}; return <div className="intelligence-detail" key={candidate.id}><span className="label">{candidate.origin} · {candidate.status}</span><h2>{candidate.organiser_name || candidate.candidate_name}</h2><p>{candidate.candidate_name}{candidate.organiser_name ? " — organiser resolved from public event evidence" : ""}</p><div className="intelligence-grid"><div><span className="label">EVENT CONNECTION</span><strong>{intelligence.eventConnection?.state ?? "UNKNOWN"}</strong></div><div><span className="label">PRIMARY OPPORTUNITY</span><strong>{intelligence.primaryEntryOpportunity ?? "UNKNOWN"} · {intelligence.commercialPriority ?? "LOW"}</strong></div><div><span className="label">EGS / TICKETING / ECC</span><strong>{intelligence.egs?.opportunityStrength ?? "Not assessed"} · {intelligence.ticketing?.opportunityStrength ?? "Not assessed"} · {intelligence.ecc?.opportunityStrength ?? "Not assessed"}</strong></div><div><span className="label">BUYER / NEXT ACTION</span><strong>{intelligence.buyerProblemOwner?.likelyRoles?.join(" · ") || "Unknown"} · {intelligence.nextBestCommercialAction?.ctaLabel || "Review"}</strong></div></div><p className="card-meta">OUTREACH · {intelligence.outreachEligibility ?? "REVIEW_REQUIRED"} · no sequence is created or sent automatically.</p>{(candidate.facts ?? []).slice(0, 3).map((fact: any, index: number) => <p key={index}>FACT · {fact.claim} {fact.sourceUrl ? <a href={fact.sourceUrl} target="_blank" rel="noreferrer">Source</a> : null}</p>)}{(candidate.inferences ?? []).slice(0, 2).map((item: any, index: number) => <p key={`i-${index}`}>INFERENCE · {item.claim}</p>)}</div>; })}</article>)}
  </section>;
}
