"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { formatDate } from "../../../src/operator-ui/logic";
import { LEAD_CLASSIFICATIONS, classificationRequiresReason, describeDataQuality, enrichmentEligibility, leadClassificationLabels } from "../../../src/incoming-leads/workspace";

type Lead = Record<string, any>;
type Member = { user_id: string; member_role: string; active: boolean };
type WorkspaceData = { access: "VIEWER" | "OPERATOR" | "ADMIN"; leads: Lead[]; totalCount: number; metrics: Record<string, number>; members: Member[]; page: number; pageSize: number };

const sourceLabels: Record<string, string> = { DEMO_REQUEST: "Demo request", TALK_TO_SALES: "Talk to sales", TRIAL_STARTED: "Trial started", PRODUCT_ENQUIRY: "Product enquiry", RESOURCE_DOWNLOAD: "Resource download", TEMPLATE_DOWNLOAD: "Template download", NEWSLETTER_SIGNUP: "Newsletter signup", INTERNAL_TEST: "Internal / test" };
const stageLabels: Record<string, string> = { NEW: "New", REVIEWING: "Reviewing", QUALIFIED: "Qualified", CONTACTED: "Contacted", DEMO_SCHEDULED: "Demo scheduled", TRIAL_ACTIVE: "Trial active", PROPOSAL: "Proposal", NURTURE: "Nurture", CONVERTED: "Converted", DISQUALIFIED: "Disqualified", LOST: "Lost" };
const intentLabels: Record<string, string> = { VERY_HIGH: "Very high intent", HIGH: "High intent", MEDIUM: "High engagement", LOW: "Low intent", NURTURE: "Nurture", EXCLUDED: "Excluded" };
const enrichmentLabels: Record<string, string> = { NOT_ELIGIBLE: "Not eligible", BLOCKED_UNTIL_IDENTITY_RESOLVED: "Resolve identity first", EVIDENCE_AVAILABLE: "Evidence available", NOT_ENRICHED: "Not enriched" };
const views = [["needs-review", "Needs review"], ["active-leads", "Active leads"], ["high-intent", "High intent"], ["follow-up-due", "Follow-up due"], ["incomplete-data", "Incomplete data"], ["existing-customers", "Existing customers"], ["excluded", "Excluded"], ["all", "All records"]] as const;

function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: string }) { return <span className={`operator-badge ${tone}`}>{children}</span>; }
function Loading() { return <div className="operator-empty"><span className="operator-kicker">PLEASE WAIT</span><p>Loading Incoming Leads…</p></div>; }
function Empty({ text = "No incoming leads match this view." }: { text?: string }) { return <div className="operator-empty"><span className="operator-kicker">NO RESULTS</span><h2>{text}</h2><p>Try another queue or adjust the filters. Source submissions are retained even when a record is excluded.</p></div>; }
function isOverdue(lead: Lead) { return Boolean(lead.follow_up_at && new Date(lead.follow_up_at).getTime() < Date.now() && !["CONVERTED", "DISQUALIFIED", "LOST"].includes(lead.stage)); }

async function postIncoming(body: Record<string, unknown>) {
  const response = await fetch("/api/incoming-leads", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json();
  if (!response.ok) throw new Error(result.message || "Incoming lead action failed.");
  return result;
}

function useIncomingData(query: string) {
  const [data, setData] = useState<WorkspaceData>({ access: "VIEWER", leads: [], totalCount: 0, metrics: {}, members: [], page: 1, pageSize: 25 });
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const refresh = useCallback(async () => {
    setState("loading");
    try {
      const response = await fetch(`/api/incoming-leads?${query}`);
      if (!response.ok) throw new Error();
      setData(await response.json());
      setState("ready");
    } catch { setState("error"); }
  }, [query]);
  useEffect(() => { void refresh(); }, [refresh]);
  return { data, state, refresh };
}

function Header({ title, lede, action }: { title: string; lede: string; action?: React.ReactNode }) {
  return <header className="operator-page-header"><div><span className="operator-kicker">INCOMING LEADS</span><h1>{title}</h1><p>{lede}</p></div>{action}</header>;
}

function QualityLabels({ lead }: { lead: Lead }) {
  const quality = lead.data_quality_issues?.length ? lead.data_quality_issues : describeDataQuality(lead);
  return <div className="incoming-quality"><Badge tone={quality.length ? "review_required" : "qualified"}>{quality.length ? `${quality.length} data gap${quality.length === 1 ? "" : "s"}` : "Data complete"}</Badge><small>{quality.length ? quality[0] : enrichmentLabels[lead.enrichment_state] ?? "Ready for review"}</small></div>;
}

function LeadRow({ lead, selected, onSelect }: { lead: Lead; selected: boolean; onSelect: (checked: boolean) => void }) {
  const source = sourceLabels[lead.highest_intent_source_category] ?? lead.highest_intent_source_category;
  return <tr><td><input aria-label={`Select ${lead.display_name || lead.organisation_name || "incoming lead"}`} type="checkbox" checked={selected} onChange={(event) => onSelect(event.target.checked)} /></td><td><strong>{lead.display_name || "Contact not yet identified"}</strong><span>{lead.organisation_name || "Organisation not yet resolved"}</span><small>{lead.contact_email || "No email retained"}</small></td><td><span>Original: {sourceLabels[lead.originating_source_category] ?? lead.originating_source_category}</span><small>Latest: {sourceLabels[lead.latest_source_category] ?? lead.latest_source_category}</small><small>{lead.activity_count} interaction{lead.activity_count === 1 ? "" : "s"} · highest {source}</small></td><td><Badge tone={String(lead.current_intent).toLowerCase()}>{intentLabels[lead.current_intent] ?? lead.current_intent}</Badge><small>{lead.priority_reason}</small></td><td><Badge tone={String(lead.lead_classification).toLowerCase()}>{leadClassificationLabels[lead.lead_classification as keyof typeof leadClassificationLabels] ?? lead.lead_classification}</Badge><small>{stageLabels[lead.stage] ?? lead.stage}</small></td><td><span>{lead.owner_id ? String(lead.owner_id).slice(0, 8) : "Unassigned"}</span><small>{lead.follow_up_at ? `${isOverdue(lead) ? "Overdue" : "Due"} · ${formatDate(lead.follow_up_at)}` : lead.next_action || "No next action"}</small></td><td><span>{formatDate(lead.last_activity_at)}</span><small>{enrichmentLabels[lead.enrichment_state] ?? lead.enrichment_state}</small></td><td><QualityLabels lead={lead} /></td><td><Link className="table-action" href={`/operator/incoming-leads/${lead.id}`}>Inspect ↗</Link></td></tr>;
}

function BulkActions({ selectedIds, members, refresh }: { selectedIds: string[]; members: Member[]; refresh: () => Promise<void> }) {
  const [ownerId, setOwnerId] = useState("");
  const [classification, setClassification] = useState("NEEDS_REVIEW");
  const [reason, setReason] = useState("");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const run = async (bulkAction: string, value: Record<string, unknown>) => {
    if (!selectedIds.length || !window.confirm(`${bulkAction.replaceAll("_", " ")} ${selectedIds.length} selected record${selectedIds.length === 1 ? "" : "s"}?`)) return;
    setBusy(true); setMessage("");
    try { const result = await postIncoming({ action: "BULK", leadIds: selectedIds, bulkAction, value }); setMessage(result.message); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Bulk update failed."); } finally { setBusy(false); }
  };
  if (!selectedIds.length) return null;
  return <section className="incoming-bulk-actions" aria-label="Bulk incoming lead actions"><strong>{selectedIds.length} selected</strong><label>Assign owner<select value={ownerId} onChange={(event) => setOwnerId(event.target.value)}><option value="">Unassigned</option>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.user_id.slice(0, 8)} · {member.member_role}</option>)}</select></label><button className="operator-button secondary" disabled={busy} type="button" onClick={() => void run("ASSIGN_OWNER", { ownerId })}>Assign owner</button><button className="operator-button secondary" disabled={busy} type="button" onClick={() => void run("MARK_REVIEWED", {})}>Mark reviewed</button><label>Classification<select value={classification} onChange={(event) => setClassification(event.target.value)}>{LEAD_CLASSIFICATIONS.map((value) => <option key={value} value={value}>{leadClassificationLabels[value]}</option>)}</select></label><label>Reason{classificationRequiresReason(classification) ? " (required)" : ""}<input value={reason} onChange={(event) => setReason(event.target.value)} maxLength={1000} placeholder="Why this disposition applies" /></label><button className="operator-button" disabled={busy || (classificationRequiresReason(classification) && !reason.trim())} type="button" onClick={() => void run("CLASSIFY", { classification, reason })}>Classify selected</button>{message ? <span role="status">{message}</span> : null}</section>;
}

export function IncomingLeadsView() {
  const [view, setView] = useState("needs-review"); const [search, setSearch] = useState(""); const [source, setSource] = useState("ALL"); const [classification, setClassification] = useState("ALL"); const [intent, setIntent] = useState("ALL"); const [owner, setOwner] = useState("ALL"); const [stage, setStage] = useState("ALL"); const [followUpState, setFollowUpState] = useState("ALL"); const [dataQualityState, setDataQualityState] = useState("ALL"); const [enrichmentState, setEnrichmentState] = useState("ALL"); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [selected, setSelected] = useState<Set<string>>(new Set());
  const query = useMemo(() => new URLSearchParams({ view, search, source, classification, intent, owner, stage, followUpState, dataQualityState, enrichmentState, dateFrom, dateTo, page: String(page), pageSize: String(pageSize) }).toString(), [classification, dataQualityState, dateFrom, dateTo, enrichmentState, followUpState, intent, owner, page, pageSize, search, source, stage, view]);
  const { data, state, refresh } = useIncomingData(query);
  useEffect(() => setSelected(new Set()), [query]);
  if (state === "loading") return <Loading />; if (state === "error") return <Empty text="Incoming Leads data is unavailable." />;
  const readOnly = data.access === "VIEWER"; const totalPages = Math.max(1, Math.ceil(data.totalCount / pageSize)); const metrics = data.metrics;
  const selectAll = (checked: boolean) => setSelected(checked ? new Set(data.leads.map((lead) => lead.id)) : new Set());
  const setLeadSelected = (id: string, checked: boolean) => setSelected((current) => { const next = new Set(current); checked ? next.add(id) : next.delete(id); return next; });
  return <><Header title="What needs review?" lede="Classify each incoming record before enrichment or opportunity work. Interactions stay attached to one lead; excluded records remain auditable." action={readOnly ? <span className="incoming-read-only">Read-only viewer access</span> : undefined} />
    {readOnly ? <p className="incoming-read-only" role="status">Viewers can inspect source evidence and history but cannot change classification, ownership or follow-up.</p> : null}
    <section className="incoming-metrics" aria-label="Incoming lead operational metrics"><div><span>New / unreviewed</span><strong>{metrics.newUnreviewed ?? 0}</strong><small>Awaiting an operator review</small></div><div><span>Active genuine leads</span><strong>{metrics.activeGenuineLeads ?? 0}</strong><small>Excludes tests, internal and non-leads</small></div><div><span>High-intent leads</span><strong>{metrics.highIntentLeads ?? 0}</strong><small>High or very high demonstrated intent</small></div><div><span>Follow-ups due</span><strong>{metrics.followUpsDue ?? 0}</strong><small>Open operational follow-ups</small></div><div><span>Needs classification</span><strong>{metrics.needsClassification ?? 0}</strong><small>Not yet confirmed as a prospect or non-lead</small></div><div><span>Incomplete / needs enrichment</span><strong>{metrics.incompleteNeedsEnrichment ?? 0}</strong><small>Data gaps shown per record</small></div></section>
    <div className="incoming-view-tabs" role="tablist" aria-label="Incoming lead views">{views.map(([value, label]) => <button type="button" key={value} className={view === value ? "active" : undefined} onClick={() => { setView(value); setPage(1); }}>{label}</button>)}</div>
    <section className="incoming-filters"><label>Search<input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Name, email, organisation or source" /></label><label>Source<select value={source} onChange={(event) => { setSource(event.target.value); setPage(1); }}><option value="ALL">All sources</option>{Object.entries(sourceLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Classification<select value={classification} onChange={(event) => { setClassification(event.target.value); setPage(1); }}><option value="ALL">All classifications</option>{LEAD_CLASSIFICATIONS.map((value) => <option key={value} value={value}>{leadClassificationLabels[value]}</option>)}</select></label><label>Intent<select value={intent} onChange={(event) => { setIntent(event.target.value); setPage(1); }}><option value="ALL">All intent</option>{Object.entries(intentLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Owner<select value={owner} onChange={(event) => { setOwner(event.target.value); setPage(1); }}><option value="ALL">All owners</option><option value="UNASSIGNED">Unassigned</option>{data.members.map((member) => <option key={member.user_id} value={member.user_id}>{member.user_id.slice(0, 8)} · {member.member_role}</option>)}</select></label><label>Stage<select value={stage} onChange={(event) => { setStage(event.target.value); setPage(1); }}><option value="ALL">All stages</option>{Object.entries(stageLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Follow-up<select value={followUpState} onChange={(event) => { setFollowUpState(event.target.value); setPage(1); }}><option value="ALL">Any follow-up</option><option value="DUE">Due now</option><option value="SCHEDULED">Scheduled</option><option value="NONE">None set</option></select></label><label>Data quality<select value={dataQualityState} onChange={(event) => { setDataQualityState(event.target.value); setPage(1); }}><option value="ALL">Any data state</option><option value="INCOMPLETE">Incomplete</option><option value="COMPLETE">Complete</option></select></label><label>Enrichment<select value={enrichmentState} onChange={(event) => { setEnrichmentState(event.target.value); setPage(1); }}><option value="ALL">Any enrichment state</option>{Object.entries(enrichmentLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>From date<input type="date" value={dateFrom} onChange={(event) => { setDateFrom(event.target.value); setPage(1); }} /></label><label>To date<input type="date" value={dateTo} onChange={(event) => { setDateTo(event.target.value); setPage(1); }} /></label></section>
    {!readOnly ? <BulkActions selectedIds={[...selected]} members={data.members} refresh={refresh} /> : null}
    <section className="incoming-section"><div className="section-heading"><span className="operator-kicker">{views.find(([value]) => value === view)?.[1].toUpperCase()}</span><span className="muted">{data.totalCount} matching records · database-filtered</span></div>{data.leads.length ? <><div className="collection-table-wrap incoming-table"><table className="collection-table"><caption className="sr-only">Incoming leads</caption><thead><tr><th><input aria-label="Select all visible incoming leads" type="checkbox" checked={data.leads.length > 0 && data.leads.every((lead) => selected.has(lead.id))} onChange={(event) => selectAll(event.target.checked)} disabled={readOnly} /></th><th>CONTACT / ORGANISATION</th><th>SOURCE / INTERACTIONS</th><th>INTENT</th><th>CLASSIFICATION</th><th>OWNER / NEXT ACTION</th><th>LAST ACTIVITY</th><th>DATA / ENRICHMENT</th><th>ACTION</th></tr></thead><tbody>{data.leads.map((lead) => <LeadRow key={lead.id} lead={lead} selected={selected.has(lead.id)} onSelect={(checked) => setLeadSelected(lead.id, checked)} />)}</tbody></table></div><div className="pagination"><span>Showing {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, data.totalCount)} of {data.totalCount}</span><label>Rows <select value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Next</button></div></> : <Empty />}</section>
  </>;
}

function DetailAction({ label, action, leadId, value = {}, disabled, onDone }: { label: string; action: string; leadId: string; value?: Record<string, unknown>; disabled?: boolean; onDone: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  return <><button className="operator-button secondary" type="button" disabled={busy || disabled} onClick={() => { if (!window.confirm(`${label}?`)) return; setBusy(true); void postIncoming({ action, leadId, value }).then(async (result) => { setMessage(result.message); await onDone(); }).catch((error) => setMessage(error instanceof Error ? error.message : "Action failed.")).finally(() => setBusy(false)); }}>{busy ? "Saving…" : label}</button>{message ? <small role="status">{message}</small> : null}</>;
}

export function IncomingLeadDetailView({ leadId }: { leadId: string }) {
  const [data, setData] = useState<Record<string, any>>({ changes: [], notes: [], submissions: [], activities: [], members: [], evidence: [] }); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [note, setNote] = useState(""); const [nextAction, setNextAction] = useState(""); const [followUp, setFollowUp] = useState(""); const [classification, setClassification] = useState(""); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  const refresh = useCallback(async () => { setState("loading"); try { const response = await fetch(`/api/incoming-leads?leadId=${encodeURIComponent(leadId)}`); if (!response.ok) throw new Error(); setData(await response.json()); setState("ready"); } catch { setState("error"); } }, [leadId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const save = async (action: string, value: Record<string, unknown>) => { const result = await postIncoming({ action, leadId, value }); setMessage(result.message); await refresh(); };
  if (state === "loading") return <Loading />; if (state === "error" || !data.lead) return <Empty text="Incoming lead detail is unavailable." />;
  const lead = data.lead as Lead; const policy = lead.communication_policy ?? {}; const readOnly = data.access === "VIEWER"; const selectedClassification = classification || lead.lead_classification || "NEEDS_REVIEW"; const quality = describeDataQuality({ ...lead, account_website: data.account?.website, contact_role_title: data.contact?.role_title }); const enrichment = enrichmentEligibility({ ...lead, enrichment_evidence_count: data.evidence?.length }); const timeline: Lead[] = [...data.submissions.map((item: Lead) => ({ ...item, timelineType: "Source interaction", time: item.occurred_at, label: sourceLabels[item.source_category] ?? item.source_category })), ...data.activities.map((item: Lead) => ({ ...item, timelineType: "Activity", time: item.occurred_at, label: item.activity_type }))].sort((a, b) => new Date(b.time).getTime() - new Date(a.time).getTime());
  const excluded = enrichment === "NOT_ELIGIBLE";
  return <><Header title={lead.display_name || "Incoming contact"} lede={`${lead.organisation_name || "Organisation not yet resolved"} · ${lead.product_code === "event-suite" ? "Event Suite" : lead.product_code}`} action={<Link className="operator-button secondary" href="/operator/incoming-leads">Back to Incoming Leads</Link>} />
    {readOnly ? <p className="incoming-read-only">Read-only viewer access. Classification and operational controls are unavailable.</p> : null}
    <div className="incoming-detail-grid"><main><section className="incoming-detail-card incoming-summary"><div><span className="operator-label">ORIGINAL ACQUISITION</span><strong>{sourceLabels[lead.originating_source_category] ?? lead.originating_source_category}</strong><p>{lead.originating_source_detail || "Source detail not recorded"}</p></div><div><span className="operator-label">LATEST INTERACTION</span><strong>{sourceLabels[lead.latest_source_category] ?? lead.latest_source_category}</strong><p>{lead.latest_source_detail || "Source detail not recorded"}</p></div><div><span className="operator-label">HIGHEST DEMONSTRATED INTENT</span><strong>{intentLabels[lead.current_intent] ?? lead.current_intent}</strong><p>{lead.activity_count} interactions · {lead.priority_reason}</p></div></section>
      <section className="incoming-detail-card"><span className="operator-kicker">IDENTITY, ACCOUNT AND LIFECYCLE</span><div className="incoming-detail-facts"><div><b>Classification</b><span>{leadClassificationLabels[lead.lead_classification as keyof typeof leadClassificationLabels] ?? "Needs review"}</span></div><div><b>Lifecycle stage</b><span>{stageLabels[lead.stage] ?? lead.stage}</span></div><div><b>Contact</b><span>{data.contact?.email || "No contact email retained"}</span></div><div><b>Organisation/account</b><span>{data.account?.name || "No confirmed account match"}</span></div><div><b>Website/domain</b><span>{data.account?.website || "Not recorded"}</span></div><div><b>Opportunity / tenant relationship</b><span>{data.opportunity ? `${data.opportunity.stage}${data.opportunity.conversion_route ? ` · ${data.opportunity.conversion_route}` : ""}` : "No incoming opportunity linked"}</span></div></div></section>
      <section className="incoming-detail-card"><span className="operator-kicker">DATA QUALITY AND ENRICHMENT</span><div className="incoming-quality-list">{quality.length ? quality.map((item) => <Badge key={item} tone="review_required">{item}</Badge>) : <Badge tone="qualified">No identified data gaps</Badge>}</div><p>{enrichmentLabels[enrichment] ?? enrichment}. Viewing this record never triggers enrichment.</p>{data.evidence.length ? <div className="incoming-evidence-list">{data.evidence.map((item: Lead) => <article key={item.id}><strong>{item.claim}</strong><span>{item.evidence_type} · confidence {item.confidence ?? "not scored"} · {formatDate(item.observed_at || item.created_at)}</span>{item.source_url ? <a href={item.source_url} target="_blank" rel="noreferrer">Open source ↗</a> : null}</article>)}</div> : <p>No research evidence is attached to this account.</p>}</section>
      <section className="incoming-detail-card"><span className="operator-kicker">COMPLETE INTERACTION TIMELINE</span><ol className="incoming-timeline">{timeline.map((item) => <li key={`${item.timelineType}-${item.id}`}><div><strong>{item.label}</strong><span>{item.timelineType} · {item.source_detail || item.summary || "Interaction retained"}</span></div><time>{formatDate(item.time)}</time></li>)}</ol></section>
      <section className="incoming-detail-card"><span className="operator-kicker">SOURCE AND ATTRIBUTION RECORDS</span>{data.submissions.map((submission: Lead) => <details className="incoming-source-record" key={submission.id}><summary>{submission.source_system} · {submission.source_record_id} · {submission.processing_state}</summary><p>{submission.source_page || "Page not recorded"} · {submission.resource_identifier || submission.template_identifier || "No resource/template"} · {submission.campaign_identifier || "No campaign"} · consent {submission.consent_state} · received {formatDate(submission.received_at)}</p></details>)}</section>
    </main><aside className="incoming-side-panel"><section className="incoming-detail-card"><span className="operator-kicker">PRIMARY OPERATOR ACTIONS</span>{readOnly ? <p>Operational controls require operator or admin access.</p> : <><label>Classification<select value={selectedClassification} onChange={(event) => setClassification(event.target.value)}>{LEAD_CLASSIFICATIONS.map((value) => <option key={value} value={value}>{leadClassificationLabels[value]}</option>)}</select></label><label>Classification reason{classificationRequiresReason(selectedClassification) ? " (required)" : ""}<textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={1000} placeholder="Why this is a prospect, customer or non-lead" /></label><button className="operator-button" type="button" disabled={classificationRequiresReason(selectedClassification) && !reason.trim()} onClick={() => void save("CLASSIFY", { classification: selectedClassification, reason }).catch((error) => setMessage(error.message))}>Save classification</button>{lead.lead_classification !== "NEEDS_REVIEW" ? <DetailAction label="Restore to needs review" action="RESTORE" leadId={lead.id} onDone={refresh} /> : null}</>}</section>
      <section className="incoming-detail-card"><span className="operator-kicker">OWNERSHIP AND FOLLOW-UP</span><label>Stage<select disabled={readOnly || excluded} value={lead.stage} onChange={(event) => void save("CHANGE_STAGE", { stage: event.target.value }).catch((error) => setMessage(error.message))}>{Object.entries(stageLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Owner<select disabled={readOnly} value={lead.owner_id || ""} onChange={(event) => void save("ASSIGN_OWNER", { ownerId: event.target.value }).catch((error) => setMessage(error.message))}><option value="">Unassigned</option>{data.members.map((member: Member) => <option key={member.user_id} value={member.user_id}>{member.user_id.slice(0, 8)} · {member.member_role}</option>)}</select></label><label>Next action<input disabled={readOnly} value={nextAction || lead.next_action || ""} onChange={(event) => setNextAction(event.target.value)} /></label><button className="operator-button" type="button" disabled={readOnly} onClick={() => void save("SET_NEXT_ACTION", { nextAction }).catch((error) => setMessage(error.message))}>Save next action</button><label>Follow-up date<input disabled={readOnly} type="datetime-local" value={followUp || (lead.follow_up_at ? new Date(lead.follow_up_at).toISOString().slice(0, 16) : "")} onChange={(event) => setFollowUp(event.target.value)} /></label><button className="operator-button" type="button" disabled={readOnly} onClick={() => void save("SET_FOLLOW_UP", { followUpAt: followUp ? new Date(followUp).toISOString() : "" }).catch((error) => setMessage(error.message))}>Save follow-up</button>{message ? <p className="incoming-status" role="status">{message}</p> : null}{!readOnly ? <div className="incoming-action-grid"><DetailAction label="Mark reviewed" action="MARK_REVIEWED" leadId={lead.id} onDone={refresh} /><DetailAction label="Mark contacted" action="MARK_CONTACTED" leadId={lead.id} disabled={excluded} onDone={refresh} /><DetailAction label="Qualify" action="QUALIFY" leadId={lead.id} disabled={excluded} onDone={refresh} /><DetailAction label="Move to nurture" action="MOVE_TO_NURTURE" leadId={lead.id} disabled={excluded} onDone={refresh} /></div> : null}</section>
      <section className="incoming-detail-card"><span className="operator-kicker">COMMUNICATION TREATMENT</span><h2>{policy.permittedTreatment || "Policy not recorded"}</h2><p className="incoming-no-send">No send, schedule, provider or message action exists in this workspace. Excluded records are never enrichment-eligible.</p></section>
      <section className="incoming-detail-card"><span className="operator-kicker">NOTES AND AUDIT HISTORY</span>{!readOnly ? <><textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} placeholder="Record a human decision or context" /><button className="operator-button" type="button" disabled={!note.trim()} onClick={() => void save("ADD_NOTE", { note }).then(() => setNote("")).catch((error) => setMessage(error.message))}>Add note</button></> : null}{data.notes.map((item: Lead) => <p className="incoming-note" key={item.id}>{item.note}<small>{formatDate(item.created_at)}</small></p>)}<details><summary>Classification and change history</summary>{data.changes.map((change: Lead) => <p className="incoming-note" key={change.id}>{String(change.action).replaceAll("_", " ")} · {formatDate(change.created_at)}</p>)}</details></section>
    </aside></div></>;
}
