"use client";
import { useEffect, useState } from "react";
import { dispositionReason, formatDate, organisationName, runCounts, statusLabel, territoryLabel, lensLabel, type OperatorCandidate, type OperatorPayload, type OperatorRun } from "../../src/operator-ui/logic";
function Badge({ children, tone="neutral" }: { children: React.ReactNode; tone?: string }) { return <span className={`operator-badge ${tone}`}>{children}</span>; }
export function RunsInventoryView() {
  const [data,setData]=useState<OperatorPayload>({access:"VIEWER",runs:[],candidates:[],latestRunId:null}); const [selected,setSelected]=useState<OperatorRun|null>(null);
  useEffect(()=>{fetch("/api/operator?view=runs").then(r=>r.json()).then(setData).catch(()=>{});},[]);
  const appearances=(selected?data.candidates.filter(item=>item.discovery_run_id===selected.id):[]) as OperatorCandidate[];
  return <><header className="operator-page-header"><div><span className="operator-kicker">AI SALES TEAM · RUNS</span><h1>Research execution history</h1><p>Runs record research appearances. They are not the prospect database.</p></div></header><div className="collection-table-wrap"><table className="operator-table"><caption>Research runs</caption><thead><tr><th>STARTED</th><th>SCOPE</th><th>STATUS</th><th>UNIQUE / APPEARANCES</th><th>REVIEW</th><th>QUALIFIED</th><th>REJECTED / BLOCKED</th><th>ACTION</th></tr></thead><tbody>{data.runs.map(run=>{const counts=runCounts(run,data.candidates); return <tr key={run.id}><td>{formatDate(run.created_at)}</td><td>{territoryLabel(run.territory_code)} · {lensLabel(run.focus)}</td><td><Badge tone={run.status.toLowerCase()}>{run.status}</Badge></td><td>{counts.found} appearances</td><td>{counts.review}</td><td>{counts.qualified}</td><td>{counts.rejected}</td><td><button type="button" className="table-action" onClick={()=>setSelected(run)}>Inspect in place</button></td></tr>})}</tbody></table></div>{selected?<aside className="operator-inspector" aria-label="Run inspection"><header><div><span className="operator-kicker">RUN INSPECTION</span><h2>{territoryLabel(selected.territory_code)} · {lensLabel(selected.focus)}</h2><p>{formatDate(selected.created_at)} · {selected.status}</p></div><button type="button" className="table-action" onClick={()=>setSelected(null)}>Close</button></header><div className="inspector-body"><p><strong>Found:</strong> {runCounts(selected,data.candidates).found} candidate appearances</p><p><strong>Ledger:</strong> {appearances.length ? `${appearances.length} persisted results` : "Historical data incomplete — aggregate counter only"}</p>{appearances.map(item=><article key={item.id}><strong>{organisationName(item)}</strong><p><Badge tone={item.status.toLowerCase()}>{statusLabel(item.status)}</Badge> {dispositionReason(item)}</p></article>)}</div></aside>:null}</>;
}
