import type { CommercialClaim, ClaimCategory, ClaimStrength } from "./commercial-model.ts";

export const commodityClaimLabels = [
  "event page builder", "AI content generation", "ticketing", "QR tickets", "RSVP", "email marketing", "all-in-one", "easy to use", "affordable", "branded event pages",
] as const;

const baseClaim = (id: string, conciseClaim: string, category: ClaimCategory, strength: ClaimStrength, notes: string): CommercialClaim => ({
  id, category, strength, conciseClaim, whatIsDifferent: "Not yet established.", customerProblem: "Requires validation.", relevantCapabilities: [], relevantClientTypes: [], territoryRelevance: ["ZA", "GB"], supportingEvidence: [], competitorComparisonStatus: "NOT_RESEARCHED", evidenceConfidence: strength === "COMMODITY" ? "HIGH" : "NONE", prohibitedWording: [], notes,
});

export const commodityClaims: CommercialClaim[] = commodityClaimLabels.map((label) => baseClaim(`commodity-${label.replaceAll(" ", "-")}`, label, "FEATURE", "COMMODITY", "Common market capability; never present as unique by itself."));

export const prohibitedCompetitiveClaim = baseClaim("prohibited-unsupported-competitive-superiority", "Competitors cannot do this", "DEFENSIBLE_DIFFERENTIATOR", "PROHIBITED", "Prohibited until direct competitor evidence supports a precise, bounded statement.");

export const eventSuiteHypotheses: CommercialClaim[] = [
  { ...baseClaim("hypothesis-event-operations-centre", "Event Operations as the centre of gravity", "SALES_WEDGE", "HYPOTHESIS", "Event Suite connects work required to manage and run events rather than only ticketing or registration."), whatIsDifferent: "Connects the operational work around an event in one commercial story.", customerProblem: "Fragmented event work across specialist tools, spreadsheets, messaging, and run sheets.", relevantCapabilities: ["event-management", "rsvp", "workforce", "production-operations"], relevantClientTypes: ["festival-organisers", "venues-multiple-events", "event-agencies"], supportingEvidence: ["Internal Phase 1 product profile"], notes: "Hypothesis; not a market-wide uniqueness claim." },
  { ...baseClaim("hypothesis-growth-operations", "Growth + Operations", "SALES_WEDGE", "HYPOTHESIS", "Growth/discoverability layer alongside operational tools."), whatIsDifferent: "Event Growth Studio is considered alongside event operations.", customerProblem: "Growth activity and delivery operations can be managed as disconnected work.", relevantCapabilities: ["event-growth-studio", "event-management", "ticketing"], relevantClientTypes: ["event-promoters", "conference-organisers", "event-agencies"], supportingEvidence: ["Internal Phase 1 product profile"], notes: "Do not claim unique market availability without evidence." },
  { ...baseClaim("hypothesis-connected-operations", "Connected Operations", "SALES_WEDGE", "HYPOTHESIS", "Potential value from connected Event Suite capabilities versus fragmented workflows."), whatIsDifferent: "A connected operating model across GROW, MANAGE, and RUN.", customerProblem: "Repeated handoffs and duplicated work across multiple specialist tools.", relevantCapabilities: ["event-management", "rsvp", "ticketing", "workforce", "production-operations", "event-growth-studio"], relevantClientTypes: ["venues-multiple-events", "corporate-event-teams", "sports-event-organisers"], supportingEvidence: [], notes: "Competitor comparison and customer evidence are deferred." },
  { ...baseClaim("hypothesis-modular-entry", "Modular entry / land-and-expand", "ADVANTAGE", "HYPOTHESIS", "Customers can start with an immediate problem rather than replace the whole stack on day one."), whatIsDifferent: "Entry can be framed around a relevant module or event need.", customerProblem: "Large platform replacement creates commercial and operational switching friction.", relevantCapabilities: ["event-management", "ticketing", "event-growth-studio"], relevantClientTypes: ["event-promoters", "venues-multiple-events"], supportingEvidence: [], notes: "Requires validation by sales and customer evidence." },
  { ...baseClaim("hypothesis-technology-human-delivery", "Technology + optional human/local delivery", "ADVANTAGE", "HYPOTHESIS", "Technology can be paired with optional local/operator support."), whatIsDifferent: "Optional service/support layer around the technology.", customerProblem: "Teams may need delivery capacity or local operational support, not software alone.", relevantCapabilities: ["workforce", "production-operations"], relevantClientTypes: ["event-agencies", "venues-multiple-events"], supportingEvidence: [], notes: "LNO approval and territory-specific terms remain required." },
  { ...baseClaim("hypothesis-high-frequency-event-value", "High-frequency event value", "SALES_WEDGE", "HYPOTHESIS", "Organisations running many events may gain disproportionately from reusable connected workflows."), whatIsDifferent: "Repeat-event context may increase the value of reusable workflows.", customerProblem: "Teams repeat planning and delivery work across event portfolios.", relevantCapabilities: ["event-management", "workforce", "production-operations"], relevantClientTypes: ["venues-multiple-events", "event-agencies", "corporate-event-teams"], supportingEvidence: [], notes: "Event frequency is a future qualification variable; no threshold is defined." },
];

export function canBeUsedAsDefensibleDifferentiator(claim: CommercialClaim): boolean {
  return claim.strength === "DEFENSIBLE" && claim.category === "DEFENSIBLE_DIFFERENTIATOR" && claim.competitorComparisonStatus === "EVIDENCE_BACKED" && claim.evidenceConfidence === "HIGH";
}
